const API_URL=import.meta.env.VITE_API_URL||"http://localhost:4000";
function getToken(){return localStorage.getItem("crm_token")}
async function request(path,options={}){const token=getToken(),headers={"Content-Type":"application/json",...(options.headers||{})};if(token)headers.Authorization="Bearer "+token;const res=await fetch(API_URL+path,{...options,headers});const data=res.headers.get("content-type")?.includes("application/json")?await res.json():null;if(!res.ok)throw new Error(data?.error||"Request failed ("+res.status+")");return data}
export const api={
 signup:b=>request("/api/auth/signup",{method:"POST",body:JSON.stringify(b)}),login:b=>request("/api/auth/login",{method:"POST",body:JSON.stringify(b)}),googleLogin:c=>request("/api/auth/google",{method:"POST",body:JSON.stringify({credential:c})}),verifyEmail:t=>request("/api/auth/verify-email",{method:"POST",body:JSON.stringify({token:t})}),resendVerification:e=>request("/api/auth/resend-verification",{method:"POST",body:JSON.stringify({email:e})}),
 dashboard:()=>request("/api/dashboard"),search:q=>request("/api/search?q="+encodeURIComponent(q)),listActivities:()=>request("/api/activities"),
 listContacts:()=>request("/api/contacts"),getContact:id=>request("/api/contacts/"+id),createContact:b=>request("/api/contacts",{method:"POST",body:JSON.stringify(b)}),updateContact:(id,b)=>request("/api/contacts/"+id,{method:"PUT",body:JSON.stringify(b)}),deleteContact:id=>request("/api/contacts/"+id,{method:"DELETE"}),
 listCompanies:()=>request("/api/companies"),createCompany:b=>request("/api/companies",{method:"POST",body:JSON.stringify(b)}),deleteCompany:id=>request("/api/companies/"+id,{method:"DELETE"}),
 listDeals:()=>request("/api/deals"),createDeal:b=>request("/api/deals",{method:"POST",body:JSON.stringify(b)}),updateDealStage:(id,stage)=>request("/api/deals/"+id+"/stage",{method:"PATCH",body:JSON.stringify({stage})}),deleteDeal:id=>request("/api/deals/"+id,{method:"DELETE"}),
 createActivity:b=>request("/api/activities",{method:"POST",body:JSON.stringify(b)}),completeActivity:id=>request("/api/activities/"+id+"/complete",{method:"PUT"}),deleteActivity:id=>request("/api/activities/"+id,{method:"DELETE"}),
 listLeads:()=>request("/api/leads"),createLead:b=>request("/api/leads",{method:"POST",body:JSON.stringify(b)}),convertLead:(id,b)=>request("/api/leads/"+id+"/convert",{method:"POST",body:JSON.stringify(b||{})}),deleteLead:id=>request("/api/leads/"+id,{method:"DELETE"}),
 listProducts:()=>request("/api/products"),createProduct:b=>request("/api/products",{method:"POST",body:JSON.stringify(b)}),deleteProduct:id=>request("/api/products/"+id,{method:"DELETE"}),
 listCases:()=>request("/api/cases"),createCase:b=>request("/api/cases",{method:"POST",body:JSON.stringify(b)}),updateCaseStatus:(id,status)=>request("/api/cases/"+id+"/status",{method:"PATCH",body:JSON.stringify({status})}),
 getForecast:()=>request("/api/forecast"),listTeam:()=>request("/api/team"),inviteTeammate:b=>request("/api/team/invite",{method:"POST",body:JSON.stringify(b)}),acceptInvite:b=>request("/api/team/accept-invite",{method:"POST",body:JSON.stringify(b)}),removeTeammate:id=>request("/api/team/"+id,{method:"DELETE"}),getBillingStatus:()=>request("/api/billing/status"),createBillingOrder:s=>request("/api/billing/create-order",{method:"POST",body:JSON.stringify({seats:s})}),verifyPayment:b=>request("/api/billing/verify-payment",{method:"POST",body:JSON.stringify(b)}),getReportOptions:()=>request("/api/reports/options"),runReport:(s,g,m)=>request("/api/reports/run?source="+s+"&groupBy="+g+"&metric="+m)
};
export function saveSession(token,user){localStorage.setItem("crm_token",token);localStorage.setItem("crm_user",JSON.stringify(user))}
export function clearSession(){localStorage.removeItem("crm_token");localStorage.removeItem("crm_user")}
export function getSessionUser(){const raw=localStorage.getItem("crm_user");return raw?JSON.parse(raw):null}
export function isAuthenticated(){return !!getToken()}